import type { AccountWorkspace } from "./contracts";

export const gulfLogisticsWorkspace: AccountWorkspace = {
  id: "gulf-logistics",
  name: "Gulf Logistics",
  domain: "gulflogistics.example",
  region: "Dubai · GCC · Europe",
  sellerCompany: "Supply X",
  sellerProduct: "Relay",
  researchStatus: "fixture",
  sources: [
    {
      id: "supplyx-product-overview",
      group: "seller",
      title: "Supply X Product Overview.pdf",
      filename: "Supply X Product Overview.pdf",
      format: "pdf",
      detail: "Supply X · 6 pages",
      truth: "SELLER_CONTEXT",
      content: "SUPPLY X — RELAY PRODUCT OVERVIEW\n\nRelay is Supply X’s supply-chain visibility and operations-control platform. It gives operations teams one view across ocean, air, and road shipments.\n\nCORE VALUE\n• See multi-modal shipments across regions.\n• Monitor ETA changes and delays.\n• Detect operational exceptions.\n• Prioritize alerts by operational impact.\n• Review route and location performance.\n• Track executive operational KPIs.\n\nPOSITIONING\nRelay helps distributed logistics teams move from fragmented status checks to a shared, exception-first operating rhythm.",
      excerpt: "Relay gives operations teams multi-modal visibility, ETA monitoring, prioritized exceptions, route performance, and executive operational KPIs.",
    },
    {
      id: "supplyx-technical-capabilities",
      group: "seller",
      title: "Platform Capabilities.pdf",
      filename: "Platform Capabilities.pdf",
      format: "pdf",
      detail: "Supply X · approved capability boundary",
      truth: "SELLER_CONTEXT",
      content: "RELAY TECHNICAL CAPABILITIES\n\nAPPROVED FOR DEMONSTRATION\n1. Multi-modal shipment visibility\n2. ETA and delay monitoring\n3. Operational exception detection\n4. Prioritized alerts\n5. Route and location performance\n6. Cross-region operational visibility\n7. Executive operational KPIs\n\nBOUNDARY\nDo not imply automated carrier booking, inventory optimization, procurement, or autonomous shipment intervention.",
      excerpt: "Approved Relay capabilities are limited to visibility, ETA monitoring, exception detection, prioritized alerts, route performance, cross-region visibility, and executive KPIs.",
    },
    {
      id: "supplyx-presales-notes",
      group: "seller",
      title: "Enterprise Use Cases.md",
      filename: "Enterprise Use Cases.md",
      format: "markdown",
      detail: "Supply X · demo guidance",
      truth: "SELLER_CONTEXT",
      content: "# Relay presales notes\n\n## Recommended opening\nLead with active operational exceptions, not a generic feature tour.\n\n## Demo sequence\n1. Open the prioritized exception queue.\n2. Trace one delayed shipment across regions.\n3. Close on route performance and executive KPIs.\n\n## Trust rule\nLabel all generated shipment and exception records as synthetic.",
      excerpt: "Lead with active operational exceptions, then trace one shipment and close on network-level route and KPI performance.",
    },
    {
      id: "supplyx-solution-architecture",
      group: "seller",
      title: "Solution Architecture.html",
      filename: "Solution Architecture.html",
      format: "html",
      detail: "Supply X · reference architecture",
      truth: "SELLER_CONTEXT",
      content: "<article><h1>Relay solution architecture</h1><p>Relay presents normalized shipment events through an operations-control workspace.</p><h2>Experience layers</h2><ol><li>Cross-region visibility</li><li>ETA and delay signals</li><li>Exception prioritization</li><li>Route and executive performance views</li></ol><aside>Architecture shown for presales reference. Integration specifics require discovery.</aside></article>",
      excerpt: "Relay organizes normalized shipment events into visibility, ETA, exception, route-performance, and executive views.",
    },
    {
      id: "gulf-company-profile",
      group: "prospect",
      title: "Gulf Logistics Company Brief.pdf",
      filename: "Gulf Logistics Company Brief.pdf",
      format: "pdf",
      detail: "Gulf Logistics · synthetic fixture",
      truth: "SYNTHETIC",
      content: "GULF LOGISTICS — COMPANY PROFILE\n\nSYNTHETIC HACKATHON DOCUMENT\n\nGulf Logistics is a fictional Dubai-based enterprise logistics operator with Jebel Ali operations, GCC warehousing and freight activity, and trade lanes into Europe. Multiple regional teams coordinate shipment movement across these nodes.\n\nThis profile exists only to demonstrate ContextSE and must not be presented as real customer information.",
      excerpt: "Synthetic Dubai-based logistics operator with Jebel Ali operations, GCC warehousing and freight activity, and European trade lanes.",
    },
    {
      id: "gulf-discovery-notes",
      group: "prospect",
      title: "Discovery Call Notes.md",
      filename: "Discovery Call Notes.md",
      format: "markdown",
      detail: "Gulf Logistics · synthetic discovery",
      truth: "SYNTHETIC",
      content: "# Discovery notes\n\n> Synthetic account context for the hackathon.\n\n## Current situation\nRegional operations teams use separate views and escalate shipment risk inconsistently.\n\n## Meeting audience\nCOO and operations leadership.\n\n## Desired outcome\nUnderstand whether a shared exception-first view can improve cross-region coordination without adding another reporting workflow.",
      excerpt: "Synthetic discovery indicates separate regional views and inconsistent escalation of cross-region shipment risk.",
    },
    {
      id: "gulf-platform-requirements",
      group: "prospect",
      title: "Platform Requirements.pdf",
      filename: "Platform Requirements.pdf",
      format: "pdf",
      detail: "Gulf Logistics · synthetic requirements",
      truth: "SYNTHETIC",
      content: "GULF LOGISTICS — PLATFORM REQUIREMENTS\n\nSYNTHETIC HACKATHON DOCUMENT\n\nPRIORITY REQUIREMENTS\n• Shared visibility across GCC and Europe-bound movements.\n• Early identification of ETA risk and operational delay.\n• Prioritized exception review for regional teams.\n• Route and location performance for weekly operations review.\n• Executive-level operational KPIs.\n\nAll requirements are fictional and exist only for demonstration.",
      excerpt: "Synthetic requirements prioritize shared visibility, ETA risk, exception review, route performance, and executive operational KPIs.",
    },
    {
      id: "gulf-executive-priorities",
      group: "prospect",
      title: "CEO Priorities.pdf",
      filename: "CEO Priorities.pdf",
      format: "pdf",
      detail: "Gulf Logistics · synthetic executive context",
      truth: "SYNTHETIC",
      content: "# Executive priorities\n\nSynthetic priorities for the Gulf Logistics fixture:\n\n- Reduce time spent reconciling regional shipment status.\n- Surface the exceptions that require leadership attention.\n- Compare performance across routes and operating locations.\n- Keep the executive story concise and operationally credible.\n\nNo financial outcome has been validated.",
      excerpt: "Synthetic executive priorities focus on cross-region alignment, leadership-level exceptions, and credible route performance.",
    },
    {
      id: "gulf-current-operations",
      group: "prospect",
      title: "Current Operations.html",
      filename: "Current Operations.html",
      format: "html",
      detail: "Gulf Logistics · synthetic operating model",
      truth: "SYNTHETIC",
      content: "<article><h1>Gulf Logistics current operations</h1><p><strong>Synthetic hackathon document.</strong></p><h2>Operating footprint</h2><ul><li>Jebel Ali gateway operations</li><li>GCC warehousing and regional freight</li><li>Europe-bound trade lanes</li></ul><h2>Current review rhythm</h2><p>Regional teams reconcile ETA changes and exceptions before the daily operations review. Leadership needs one prioritized cross-region picture.</p></article>",
      excerpt: "Synthetic current operations span Jebel Ali, GCC regional freight, and Europe-bound trade lanes with distributed exception review.",
    },
    {
      id: "gulf-meeting-brief",
      group: "prospect",
      title: "Meeting Brief.pdf",
      filename: "Meeting Brief.pdf",
      format: "pdf",
      detail: "Gulf Logistics · ContextSE generated brief",
      truth: "SYNTHETIC",
      content: "GULF LOGISTICS × SUPPLY X — MEETING BRIEF\n\nSYNTHETIC ACCOUNT BRIEF\n\nAUDIENCE\nCEO and COO stakeholders at Gulf Logistics\n\nOBJECTIVE\nDemonstrate how Relay can surface cross-region shipment risk and focus the operating review on the exceptions that matter most.\n\nRECOMMENDED STORY\n1. Open on prioritized operational exceptions.\n2. Trace a Jebel Ali to Hamburg shipment with ETA risk.\n3. Close on route performance and executive operational KPIs.\n\nQUESTIONS TO VALIDATE\n• Which lanes create the most coordination overhead?\n• How are priority exceptions escalated today?\n• Which operational KPIs should lead the executive review?\n\nTRUTH NOTE\nGulf Logistics and every operational record are synthetic. Relay capabilities come from Supply X approved source material.",
      excerpt: "Meeting brief for Supply X’s Relay conversation with Gulf Logistics leadership: exceptions, one cross-region shipment, then executive KPIs.",
    },
  ],
  insights: [
    { title: "Cross-region control is the likely executive theme", detail: "Gulf Logistics’ synthetic operating profile spans GCC nodes and European trade lanes, making network-level visibility the clearest opening story.", truth: "INFERENCE", sourceIds: ["gulf-company-profile", "gulf-platform-requirements"] },
    { title: "Exceptions should lead the demo", detail: "Prioritized operational exceptions connect Relay’s approved capabilities to the prospect fixture’s coordination challenge without implying unsupported automation.", truth: "INFERENCE", sourceIds: ["supplyx-technical-capabilities", "gulf-discovery-notes"] },
  ],
  strategy: {
    persona: "COO",
    objective: "Show how Gulf Logistics can identify and prioritize cross-region shipment risk before reviewing route performance.",
    thesis: "Lead with the morning exception queue, trace one Jebel Ali–Hamburg delay, then close on executive network KPIs.",
    moments: [
      { title: "Open on prioritized exceptions", capability: "Operational exception detection + prioritized alerts", why: "Makes the coordination problem visible in the first 30 seconds.", sourceIds: ["supplyx-technical-capabilities", "gulf-discovery-notes"] },
      { title: "Trace Jebel Ali to Hamburg", capability: "ETA and delay monitoring + multi-modal visibility", why: "Connects the story to Gulf Logistics’ synthetic GCC-to-Europe operating context.", sourceIds: ["gulf-company-profile", "supplyx-technical-capabilities"] },
      { title: "Close on network performance", capability: "Route performance + executive operational KPIs", why: "Gives the COO a concise cross-region outcome view.", sourceIds: ["supplyx-presales-notes", "gulf-executive-priorities"] },
    ],
    sourceIds: ["supplyx-technical-capabilities", "supplyx-presales-notes", "gulf-company-profile", "gulf-discovery-notes"],
    status: "recommended",
  },
  artifacts: [
    { id: "interactive-demo", type: "interactive_demo", title: "Interactive Demo", status: "ready", updatedAt: "Fixture ready" },
  ],
  demo: {
    generic: {
      mode: "generic", companyName: "Northstar Logistics", subtitle: "Global operations overview", narrative: "Monitor active shipments and network health across a generic global logistics network.", locations: ["Port Alpha", "Hub Central", "Warehouse East", "Port Delta"],
      kpis: [{ label: "Active shipments", value: "1,284", delta: "+3.2%" }, { label: "On-time", value: "91.4%", delta: "+0.8%" }, { label: "Exceptions", value: "38", delta: "-4 today" }],
      exceptions: [{ id: "EX-1042", title: "Late vessel departure", route: "Port Alpha → Hub Central", eta: "+18h", impact: "14 shipments", severity: "critical" }, { id: "EX-1038", title: "Warehouse dwell threshold", route: "Warehouse East", eta: "+6h", impact: "8 shipments", severity: "warning" }],
      shipments: [{ id: "NS-8421", mode: "Ocean", origin: "Port Alpha", destination: "Hub Central", eta: "Sep 02, 08:30", status: "Delayed" }, { id: "NS-8394", mode: "Road", origin: "Hub Central", destination: "Warehouse East", eta: "Aug 31, 14:10", status: "On track" }], synthetic: true,
    },
    personalized: {
      mode: "personalized", companyName: "Gulf Logistics", subtitle: "GCC → Europe exception control", narrative: "Start the COO’s morning with cross-region risk: prioritize exceptions from Jebel Ali through European arrival nodes, then inspect route performance.", locations: ["Jebel Ali", "Dubai South", "Riyadh Hub", "Hamburg Port"],
      kpis: [{ label: "GCC–EU shipments", value: "428", delta: "+6.1%" }, { label: "On-time to Europe", value: "89.7%", delta: "-1.8%" }, { label: "Priority exceptions", value: "12", delta: "3 critical" }],
      exceptions: [{ id: "GL-2048", title: "Jebel Ali vessel connection at risk", route: "Jebel Ali → Hamburg", eta: "+22h", impact: "18 shipments", severity: "critical" }, { id: "GL-2039", title: "Riyadh consolidation dwell", route: "Riyadh Hub → Dubai South", eta: "+7h", impact: "6 shipments", severity: "warning" }, { id: "GL-2011", title: "Hamburg arrival window stable", route: "Dubai South → Hamburg", eta: "On time", impact: "24 shipments", severity: "stable" }],
      shipments: [{ id: "GLX-4821", mode: "Ocean", origin: "Jebel Ali", destination: "Hamburg Port", eta: "Sep 03, 11:20", status: "Connection risk" }, { id: "GLX-4770", mode: "Road", origin: "Riyadh Hub", destination: "Dubai South", eta: "Aug 31, 16:40", status: "Dwell alert" }, { id: "GLX-4718", mode: "Air", origin: "Dubai South", destination: "Hamburg", eta: "Aug 31, 09:15", status: "On track" }], synthetic: true,
    },
  },
};

export const relayCapabilities = ["Multi-modal shipment visibility", "ETA and delay monitoring", "Operational exception detection", "Prioritized alerts", "Route and location performance", "Cross-region operational visibility", "Executive operational KPIs"] as const;
