import type { AccountWorkspace } from "./contracts";

function escapeHtml(value: string) {
  return value.replace(/[&<>'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[character] ?? character);
}

export function buildMeetingBriefHtml(workspace: AccountWorkspace, persona: string, date: string) {
  const moments = workspace.strategy.moments.map((moment, index) => `<li><strong>${index + 1}. ${escapeHtml(moment.title)}</strong><p>${escapeHtml(moment.why)}</p></li>`).join("");
  return `<!doctype html><html><head><meta charset="utf-8"><title>${escapeHtml(workspace.name)} meeting brief</title><style>body{font:15px/1.6 Arial,sans-serif;color:#17201c;max-width:760px;margin:48px auto;padding:0 24px}header{border-bottom:2px solid #17201c;padding-bottom:24px;margin-bottom:32px}small{color:#64706a;text-transform:uppercase;letter-spacing:.12em}h1{font-size:32px;margin:8px 0}h2{font-size:14px;text-transform:uppercase;letter-spacing:.08em;margin-top:32px}li{margin:16px 0}p{margin:4px 0}.notice{background:#f5f0df;padding:12px;margin-top:32px}</style></head><body><header><small>ContextSE · Meeting brief · ${escapeHtml(date)}</small><h1>${escapeHtml(workspace.name)} × ${escapeHtml(workspace.sellerProduct)}</h1><p>${escapeHtml(persona)} conversation · Exception-first control tower story</p></header><h2>Account thesis</h2><p>${escapeHtml(workspace.strategy.thesis)}</p><h2>Meeting objective</h2><p>${escapeHtml(workspace.strategy.objective)}</p><h2>Recommended demo sequence</h2><ol>${moments}</ol><h2>Questions to validate</h2><ul><li>Which GCC-to-Europe lanes create the most coordination overhead?</li><li>How are priority exceptions shared across regional teams today?</li><li>Which operational KPIs matter most in the executive review?</li></ul><p class="notice"><strong>Truth note:</strong> ${escapeHtml(workspace.name)} and all operational examples are synthetic. ${escapeHtml(workspace.sellerProduct)} capabilities come from approved ${escapeHtml(workspace.sellerCompany)} source material.</p></body></html>`;
}
